#!/bin/bash
# Designed to run in cron job, and check for any IP addresses that have been detected 
# trying to access wp-login.php repeatedly and that have received a 500 or 403 error 
# more than 10 times, or that are using "tools.ua.random()" as their user agent

# Check for excessive login attempts (200 code), more than 50 in 24 hours probably bad
grep "wp-login.*200" /usr/local/apache/logs/apache_mainlog | egrep -o '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' | sort | uniq -c | sort -bg | awk '$1 > 50 {system("/usr/sbin/csf -d " $2 " csf_ban_wp_login_attackers: Blocked " $2 " because tried to access wp-login.php and got 200 status code " $1 " times in last 24 hours")}'

# Check for 500 errors (Usually BruteProtect plugin)
grep "wp-login.*500" /usr/local/apache/logs/apache_mainlog | egrep -o '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' | sort | uniq -c | sort -bg | awk '$1 > 10 {system("/usr/sbin/csf -d " $2 " csf_ban_wp_login_attackers: Blocked " $2 " because accessed wp-login.php and got 500 error code " $1 " times in last 24 hours")}'

# Check for 403 errors
grep "wp-login.*403" /usr/local/apache/logs/apache_mainlog | egrep -o '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' | sort | uniq -c | sort -bg | awk '$1 > 10 {system("/usr/sbin/csf -d " $2 " csf_ban_wp_login_attackers: Blocked " $2 " because accessed wp-login.php and got 403 error code " $1 " times in last 24 hours")}'

# Check for tools.ua.random() in user agent string
grep "tools.ua.random" /usr/local/apache/logs/apache_mainlog | egrep -o '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' | sort | uniq -c | sort -bg | awk '$1 > 0 {system("/usr/sbin/csf -d " $2 " csf_ban_wp_login_attackers: Blocked " $2 " because used tools.ua.random as the user agent string " $1 " times in last 24 hours")}'

# Check for honeypot attack attempts
grep "/wordpresshp/wp-login.php?action=register" /usr/local/apache/logs/apache_mainlog | egrep -o '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' | sort | uniq -c | sort -bg | awk '$1 > 0 {system("/usr/sbin/csf -d " $2 " csf_ban_wp_login_attackers: Blocked " $2 " because trying to access honeypot fake WordPress registration " $1 " times in last 24 hours")}'

# Check for honeypot attack attempts
grep "/oldwp/wp-login.php?action=register" /usr/local/apache/logs/apache_mainlog | egrep -o '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' | sort | uniq -c | sort -bg | awk '$1 > 0 {system("/usr/sbin/csf -d " $2 " csf_ban_wp_login_attackers: Blocked " $2 "  because trying to access honeypot fake WordPress registration " $1 " times in last 24 hours")}'
