#!/bin/bash

# Fix file and directory permissions

if [[ -n $1 ]]; then
    dir=$1
else
    dir=$(pwd)
fi

echo "Fixing permissions for" $dir

find $dir -type f -regex ".*\(php\|js\|png\|jpg\|jpeg\|txt\|css\)" -exec chmod 644 {} \;
find $dir -type d -exec chmod 755 {} \;

echo "Done!"
